name: Winbindex Periodic Update

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
    - cron: '15 18 * * TUE'

concurrency: winbindex-periodic-update

jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      - name: Override out_path
        run: |
          echo ./gh-pages > .out_path_override
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: '.github/requirements.txt'
      - name: Install Python dependencies
        run: python -m pip install -r .github/requirements.txt
      - name: Install Windows dependencies
        run: |
          choco install -y aria2 tor
      - name: Set up Git config
        run: |
          git config --global user.email "69083578+winbindex-deploy-bot@users.noreply.github.com"
          git config --global user.name "winbindex-deploy-bot"

          # Make sure git clean doesn't fail on long paths.
          git config --global core.longpaths true
      - name: Run periodic update
        run: |
          WINBINDEX_TEMP='D:\' python -X utf8 -u deploy.py
        env:
          UUP_RSS_URL: ${{ secrets.UUP_RSS_URL }}
          UUP_GET_FILES_URL: ${{ secrets.UUP_GET_FILES_URL }}
